### ISSUE TITLE
Invalid XML In Frontend Layout

### ISSUE THREAD

**Issue by dsmithhayes** [unificdotcom/unific-magento2-extension-installer#1]
After installation of the module the Magento 2 site breaks. This is caused by the frontend layout file `default.xml`. The `<block>` element has an invalid parameter `type`. This should be `class` as per the Magento framework definition.

Here are some specs on my current Magento environment:

* Magento 2.2.6 Enterprise Edition
* Unific Extension `dev-master` (commit `7118a68`)

**Comment by dsmithhayes** [comment]
I have issues a pull request for this issue: https://github.com/unificdotcom/unific-magento2-extension-installer/pull/2

**Comment by RonXS** [comment]
Fixed by merging your PR into dev-master, thank you for your contribution!
